# Generated by Django 5.2 on 2025-05-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('genre', models.IntegerField(default=0)),
                ('role', models.IntegerField(default=0)),
                ('birth_date', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('skill_class', models.IntegerField(default=0)),
                ('contract_type', models.IntegerField(default=0)),
                ('contract_start', models.CharField(default='', max_length=100)),
                ('contract_end', models.CharField(default='', max_length=100)),
                ('max_hours_per_month', models.IntegerField(default=0)),
                ('max_hours_per_week', models.IntegerField(default=0)),
                ('max_hours_per_day', models.IntegerField(default=0)),
                ('max_hours_per_shift', models.IntegerField(default=0)),
                ('rest_days', models.JSONField(blank=True, default=list)),
                ('hourly_cost', models.FloatField(default=0.0)),
                ('extra_data', models.JSONField(default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.CharField(default='', max_length=100)),
                ('import_type', models.CharField(default='', max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('employees', models.JSONField(blank=True, default=dict)),
                ('start_date', models.CharField(default='', max_length=100)),
                ('end_date', models.CharField(default='', max_length=100)),
                ('shifts_data', models.JSONField(blank=True, default=dict)),
                ('closing_days', models.JSONField(blank=True, default=dict)),
                ('free_days', models.JSONField(blank=True, default=dict)),
                ('particular_days', models.JSONField(blank=True, default=dict)),
                ('state', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('start_time', models.CharField(default='', max_length=100)),
                ('end_time', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='api.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(default='', max_length=100)),
                ('end_date', models.CharField(default='', max_length=100)),
                ('sales_target', models.FloatField(default=0.0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
    ]
