# Generated by Django 5.2 on 2025-04-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='genre',
            field=models.IntegerField(default=0),
        ),
    ]
