# Generated by Django 5.2 on 2025-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rest_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
