# Generated by Django 5.2 on 2025-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_import_import_type_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='closing_days',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employees',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='free_days',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
