# Generated by Django 5.2 on 2025-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_employee_birth_date_employee_contract_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
